FROM ubuntu:18.04

ENV TZ=Etc/UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
echo $TZ > /etc/timezone && \
apt-get update && \
apt-get upgrade -y && \
apt-get -y install curl && \
curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get -y install nodejs python python3 wget sudo x11-utils apt-utils && \
rm -v /usr/bin/python && \
ln -vs /usr/bin/python2 /usr/bin/python

ADD . /build_tools
WORKDIR /build_tools

RUN cd tools/linux && \
python3 ./automate.py desktop && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*
