FROM desktopeditors:latest

RUN rm -v /build_tools/scripts/core_common/modules/v8.py /build_tools/scripts/core_common/modules/v8_89.py
ADD ./scripts/core_common/modules/v8.py /build_tools/scripts/core_common/modules/v8.py
ADD ./scripts/core_common/modules/v8_89.py /build_tools/scripts/core_common/modules/v8_89.py

RUN cd tools/linux && \
    python3 -u ./automate_p2.py desktop
