#!/bin/bash

key=$1
var=$2
val=$3

isfound=false

while read line; do
	IFS='=' read -ra values <<< "$line"
	iskey=true
	isnextval=false
	for item in "${values[@]}"; do
	if [ "$iskey" = false ]
	then
		if [ "$isnextval" = true ]
		then
			val=$item
			isfound=true
			break
		fi
		iskey=true
		continue
	fi
	if [ "$item" = "$key" ]
	then
		isnextval=true
	fi
	iskey=false
	done
done < "config"

if [ "$isfound" = false ]
then
	export $var="$val"
else
	#export $var="${val:1:(-1)}"
	export $var="${val:1:${#val}-2}"
fi
