#!/bin/bash

sudo apt-get -y install apt-transport-https \
                        autoconf2.13 \
                        build-essential \
                        ca-certificates \
                        cmake \
                        curl \
                        git \
                        glib-2.0-dev \
                        libgconf2-4 \
                        libglu1-mesa-dev \
                        libgtk2.0-dev \
                        libpulse-dev \
                        libtool \
                        libxss1 \
                        p7zip-full \
                        subversion
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm
sudo npm install -g grunt-cli

# Ubuntu 14
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get -y install openjdk-8-jdk
sudo update-alternatives --config java
sudo update-alternatives --config javac
