#!/bin/bash

SCRIPT=$(readlink -f "$0" || grealpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

source ./scripts/config_value module    OO_MODULE     "desktop builder"
source ./scripts/config_value platform  OO_PLATFORM   native
source ./scripts/config_value qt-dir    OO_QT_DIR     "set qt path"

IS_NEED_64=false
IS_NEED_32=false

if [[ "$OO_PLATFORM" == *"all"* ]]
then
IS_NEED_64=true
IS_NEED_32=true
fi

if [[ "$OO_PLATFORM" == *"x64"* ]]
then
IS_NEED_64=true
fi

if [[ "$OO_PLATFORM" == *"x86"* ]]
then
IS_NEED_32=true
fi

if [[ "$OO_PLATFORM" == *"native"* ]]
then
architecture=$(uname -m)
case "$architecture" in
  x86_64*)  IS_NEED_64=true ;;
  *)        IS_NEED_32=true ;;
esac
fi

if [[ "$IS_NEED_64" == true ]]
then
   QT_DEPLOY=$OO_QT_DIR/gcc_64/bin
   OS_DEPLOY=linux_64
   "$QT_DEPLOY/qmake" -nocache "$SCRIPTPATH/deploy.pro" "CONFIG+=$OO_CONFIG $OO_MODULE"
fi

if [[ "$IS_NEED_64" == true ]]
then
   QT_DEPLOY=$OO_QT_DIR/gcc/bin
   OS_DEPLOY=linux_32
   "$QT_DEPLOY/qmake" -nocache "$SCRIPTPATH/deploy.pro" "CONFIG+=$OO_CONFIG $OO_MODULE"
fi
