FROM nimmis/ubuntu:20.04

# basic dependencies
RUN apt-get -y update && \
    apt-get -y install wget xz-utils

# dependencies
RUN apt-get -y install \
    libc6-dev \
    libpthread-stubs0-dev \
    build-essential \
    glib-2.0-dev \
    libglu1-mesa-dev \
    libgtk-3-dev \
    libpulse-dev \
    libasound2-dev \
    libatspi2.0-dev \
    libcups2-dev \
    libdbus-1-dev \
    libicu-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libx11-xcb-dev \
    libxcb* \
    libxi-dev \
    libxrender-dev \
    libxss-dev \
	libxkbcommon-dev \
	libxkbcommon-x11-dev \
    libnotify-dev